### PR TITLE
Upgrading to react@0.14.0 and a newer devpack

### PR DESCRIPTION
**Pull request by sebinsua**
- [x] Upgraded to `react@0.14.0`.
- [x] Upgraded to the latest (released) devpack.
- [x] Implemented [weird workaround](https://github.com/sebinsua/component-stickymasthead/blob/a3978051faeaf60132202724f9fbe0dcd66ef844/index.es6#L26-L32) to get `react-sticky` to stop throwing `Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object` exceptions when running `npm run doc`. Please note, if there's a cleaner way of fixing this, then we can do so however it seems this will require a PR on somebody else's project.

### CODE REVIEW

**Comment by sebinsua** [comment]
@keithamus @umbobabo @fabiosantoscode

Please can one of you guys take a quick look and merge if you're okay?

Sorry about the workaround. If you want me to PR `captivationsoftware/react-sticky` and try to fix whatever bug is causing this I could try but it will be a breaking change and might take a while to merge. Can do it though anyway perhaps after this? What are your thoughts?

**Comment by umbobabo** [comment]
I think a possible solution could be fork captivationsoftware/react-sticky on our organization, fix it and refer to our implementation in this component.
In addition we can PR on the upstream of captivationsoftware/react-sticky (if they like our solution they can merge on upstream).
The less we are dependend on third party the better is in my opinion.

**Comment by keithamus** [comment]
Yup I concur with @umbobabo. Fix upstream, but use our forked version in the interim. Otherwise things look good.

**Comment by sebinsua** [comment]
Alright - I'll do that tomorrow.

**Comment by sebinsua** [comment]
@keithamus It turns out there was no need.

In both this repo and the other my mistake was to run `npm run provision` after updating to `react@0.14.0`. It resetted the version back to the old one. Using the latest version of React doesn't throw invariant errors, as it passes `react-dom`s `object.$$typeof` is `Symbol(React.Element)` test within `isValidReactElement`.

**Pull request merged**
